name: build

on:
  workflow_dispatch:
  push:
    paths:
    - 'src/**'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        gametype: ['VERSION_SE', 'VERSION_AE']

    steps:
    - uses: actions/checkout@v2

    - run: echo "VCPKG_ROOT=${Env:VCPKG_INSTALLATION_ROOT}" >> ${Env:GITHUB_ENV}

    - name: Init Submodules
      run: |
        git submodule init
        git submodule update

    - name: Retrieve matrix cache
      id: cache-matrix
      uses: actions/cache@v1
      with:
        path: ./build
        key: ${{ runner.os }}-build-matrix-${{ matrix.gametype }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('./CMakePresets.json', './src/CMakeLists.txt') }}

    - name: Remove packaging
      if: steps.cache-matrix.outputs.cache-hit == 'true'
      run: Remove-Item -Recurse -Force ./build/packaging

    - name: Build
      run: |
        cmake --preset vs2022-windows
        cmake --build build --config Release --target package
      env:
        Skyrim_CI_ENV: ${{ matrix.gametype }}

    - name: Prepare upload
      run: echo "build_name=$(Get-ChildItem -Path ./build/packaging/_CPack_Packages/win64/ZIP -Exclude *.zip | % { $_.BaseName })" >> ${Env:GITHUB_ENV}

    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.build_name }} - ${{ matrix.gametype }}
        path: ./build/packaging/_CPack_Packages/win64/ZIP/${{ env.build_name }}/main
