name: build

on:
  workflow_dispatch:
  push:
    paths:
    - 'src/**'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        gametype: ['VERSION_SE', 'VERSION_AE']

    steps:
    - uses: actions/checkout@v2

    - name: Prepare build
      run: |
        git submodule init
        git submodule update
        cmake --preset vs2022-windows
      env:
        Skyrim_CI_ENV: ${{ matrix.gametype }}

    - name: Build
      run: cmake --build build --config Release --target package

    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: Slick Sneaking - ${{ matrix.gametype }}
        path: ./build/packaging/_CPack_Packages/win64/ZIP/SlickSneaking/main/SKSE
